framework:
  secret: "%env(APP_SECRET)%"
  http_method_override: false

  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native

  php_errors:
    # active ou non la journalisation (log) des erreurs PHP
    log: true
    # si true, lève une exception sur les erreurs PHP au lieu de les afficher
    throw: false

  # ... éventuellement d'autres réglages ...

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
